// This file was automatically generated by IPG
// DO NOT EDIT!
#ifndef PEGPARSER_H
#define PEGPARSER_H{{BI_NEWLINE}}

#include <map>{{BI_NEWLINE}}

namespace {{name}}
{
	enum PTNodeType
	{
		{{#def}}
		PTNodeType_{{name}} = {{value}},
		{{/def}}
	};{{BI_NEWLINE}}

	struct PTNode;
	typedef std::map<PTNodeType, PTNode*> PTNodeTypeToPtr;{{BI_NEWLINE}}

	struct PTNode
	{
		char value;
		PTNodeTypeToPtr end;
	};{{BI_NEWLINE}}

	struct PTNodeVisitor
	{
		virtual void operator()(PTNode* _symbol, PTNodeType _type) = 0;
	};{{BI_NEWLINE}}

	PTNode* Parse(PTNodeType _type, PTNode* _symbol);
	PTNode* Traverse(PTNodeType _type, PTNode* _symbol, PTNodeVisitor& _visitor);
}{{BI_NEWLINE}}

#endif
