// This file was automatically generated by IPG
// DO NOT EDIT!
#ifndef PEGPARSER_H
#define PEGPARSER_H{{BI_NEWLINE}}

#include <vector>
#include <map>{{BI_NEWLINE}}

namespace {{name}}
{
	enum PTNodeType
	{
		{{#def}}
		PTNodeType_{{name}} = {{value}},
		{{/def}}
	};{{BI_NEWLINE}}

	struct Node;
	typedef std::map<PTNodeType, Node*> PTNodeTypeToPtr;{{BI_NEWLINE}}

	struct Node
	{
		char value;
		PTNodeTypeToPtr end;
	};{{BI_NEWLINE}}
	
	typedef std::pair<PTNodeType, Node*> PTNodeChild;
	typedef std::vector<PTNodeChild> PTNodeChildren;{{BI_NEWLINE}}

	Node* Parse(PTNodeType _type, Node* _symbol);
	Node* Traverse(PTNodeType _type, Node* _symbol, PTNodeChildren& _children);
}{{BI_NEWLINE}}

#endif
