// This file was automatically generated by IPG
// DO NOT EDIT!
#include "{{name}}.h"{{BI_NEWLINE}}

namespace {{name}}
{
	namespace
	{
		PTNode* ParseRange(char _rangeBegin, char _rangeEnd, PTNode* _symbol)
		{
			if (_symbol->value < _rangeBegin)
				return 0;
			if (_symbol->value > _rangeEnd)
				return 0;
			return ++_symbol;
		}{{BI_NEWLINE}}
		
		PTNode* ParseChar(char _char, PTNode* _symbol)
		{
			if (_symbol->value != _char)
				return 0;
			return ++_symbol;
		}{{BI_NEWLINE}}
		
		PTNode* ParseAnyChar(PTNode* _symbol)
		{
			if (_symbol->value == 0)
				return 0;
			return ++_symbol;
		}{{BI_NEWLINE}}
		
		PTNode* GetEnd(const PTNode* _symbol, PTNodeType _type)
		{
			PTNodeTypeToPtr::const_iterator i = _symbol->end.find(_type);
			if (i == _symbol->end.end())
				return 0;
			return i->second;
		}{{BI_NEWLINE}}
		
		void SetEnd(PTNode* _symbol, PTNodeType _type, PTNode* _end)
		{
			_symbol->end[_type] = _end;
		}{{BI_NEWLINE}}
		
		PTNode* Visit(PTNode* _symbol, PTNodeType _type, PTNodeVisitor& _visitor)
		{
			PTNode* end = GetEnd(_symbol, _type);
			if (end)
				_visitor(_symbol, _type);
			return end;
		}{{BI_NEWLINE}}
		
		{{#def}}
		PTNode* Parse_{{name}}(PTNode*);
		{{/def}}
		
{{#def}}{{BI_NEWLINE}}		PTNode* Parse_{{name}}(PTNode* p0)
		{
			{{#isMemoized}}
			PTNode* p1 = GetEnd(p0, PTNodeType_{{name}});
			if (p1)
				return p1;
			{{/isMemoized}}
			{{>parseCode}}
			{{#isMemoized}}
			SetEnd(p0, PTNodeType_{{name}}, p{{parseResultIndex}});
			{{/isMemoized}}
			return p{{parseResultIndex}};
		}
		{{/def}}
		
{{#def}}{{BI_NEWLINE}}		PTNode* Traverse_{{name}}(PTNode*, PTNodeVisitor&);{{/def}}
		
{{#def}}{{BI_NEWLINE}}		PTNode* Traverse_{{name}}(PTNode* p0, PTNodeVisitor& v)
		{
			{{#isMemoized}}
			if (!GetEnd(p0, PTNodeType_{{name}}))
				return 0;
			{{/isMemoized}}
			{{>traverseCode}}
			return p{{traverseResultIndex}};
		}
		{{/def}}
	}{{BI_NEWLINE}}
	
	PTNode* Parse(PTNodeType _type, PTNode* _symbol)
	{
		switch (_type)
		{
			{{#def}}
			case PTNodeType_{{name}}: return Parse_{{name}}(_symbol);
			{{/def}}
		}
		return 0;
	}{{BI_NEWLINE}}
	
	PTNode* Traverse(PTNodeType _type, PTNode* _symbol, PTNodeVisitor& _visitor)
	{
		switch (_type)
		{
			{{#def}}
			case PTNodeType_{{name}}: return Traverse_{{name}}(_symbol, _visitor);
			{{/def}}
		}
		return 0;
	}
}
