// This file was automatically generated by IPG on Wed Jul 20 21:23:23 2011
// (from /Users/alexk7/ipg/build/xcode/../../src/peg/peg.peg)
// DO NOT EDIT!
#ifndef BOOTSTRAP_TEST
#include <cassert>
#include <stdexcept>
#include <ostream>
#include <sstream>
#include <iomanip>
#include <algorithm>
#include <boost/format.hpp>
#endif

#ifndef BOOTSTRAP_TEST
#include <vector>
#include <bitset>
#include <boost/shared_ptr.hpp>
#include <tr1/unordered_map>
#endif

namespace PEGParser
{
	enum SymbolType
	{
		SymbolType_AND = 0,
		SymbolType_CLOSE = 1,
		SymbolType_Char = 2,
		SymbolType_Class = 3,
		SymbolType_Comment = 4,
		SymbolType_DOT = 5,
		SymbolType_Definition = 6,
		SymbolType_EndOfFile = 7,
		SymbolType_EndOfLine = 8,
		SymbolType_Expression = 9,
		SymbolType_Grammar = 10,
		SymbolType_Identifier = 11,
		SymbolType_LEFTARROW = 12,
		SymbolType_Literal = 13,
		SymbolType_NOT = 14,
		SymbolType_OPEN = 15,
		SymbolType_PLUS = 16,
		SymbolType_Prefix = 17,
		SymbolType_Primary = 18,
		SymbolType_QUESTION = 19,
		SymbolType_Range = 20,
		SymbolType_SLASH = 21,
		SymbolType_STAR = 22,
		SymbolType_Sequence = 23,
		SymbolType_Space = 24,
		SymbolType_Spacing = 25,
		SymbolType_Suffix = 26,
		SymbolTypeCount
	};

	typedef std::pair<SymbolType, const char*> Symbol;
	typedef std::vector<Symbol> Symbols;
	typedef std::tr1::unordered_map<const char*, const char*> MemoMap;

	const char* SymbolName(SymbolType _type);

	class Parser
	{
	public:
		const char* Parse(SymbolType _type, const char* _symbol, int& _complexity);
		const char* Traverse(SymbolType _type, const char* _symbol, Symbols& _children, int& _complexity);
		void Print(std::ostream& _os, SymbolType _type, const char* _pNode, int _tabs = 0, int _maxLineSize = 100);

	private:
		int SetEnd(SymbolType _type, const char* _pBegin, const char* _pEnd, int _complexity);
		const char* Visit(SymbolType _type, const char* _p, Symbols& _v);
		MemoMap memoMap[SymbolTypeCount];
	};

	class Iterator
	{
	public:
		Iterator(SymbolType _type, const char* _pNode = 0);
		Iterator(const Iterator& _iOther);
		operator bool() const;
		Iterator& operator++();
		SymbolType GetType() const;
		const char* Begin() const;
		const char* End() const;
		Iterator GetChild(SymbolType _childT);
		Iterator GetNext(SymbolType _childT);
		void Print(std::ostream& _os, int _tabs = 0, int _maxLineSize = 100);

	private:
		Iterator(boost::shared_ptr<Parser> _pParser, boost::shared_ptr<Symbols> _pSiblings, SymbolType _childType);
		Iterator(const Iterator& _iOther, SymbolType _childType);
		void GoToNext(SymbolType _childType);
		void SkipSiblingsWithWrongType(SymbolType _childType);
		boost::shared_ptr<Symbols> GetChildren();

		SymbolType mType;
		const char* mpNode;
		boost::shared_ptr<Symbols> mpSiblings;
		Symbols::iterator miCurrent;
		boost::shared_ptr<Symbols> mpChildren;
		boost::shared_ptr<Parser> mpParser;
	};

	std::ostream& operator<<(std::ostream& _os, const Iterator& _i);
}

namespace
{
	struct EscapeChar
	{
		EscapeChar(char _c);
		char c;
	};

	EscapeChar::EscapeChar(char _c) : c(_c)
	{
	}

	std::ostream& operator<<(std::ostream& _os, EscapeChar _e)
	{
		char c = _e.c;
		switch (c)
		{
			case '\\': c = '\\'; break;
			case '\n': c = 'n';  break;
			case '\r': c = 'r';  break;
			case '\t': c = 't';  break;
			case '\'': c = '\''; break;
			case '\"': c = '\"'; break;
			default:
				_os.put(c);
				return _os;
		}
		_os.put('\\');
		_os.put(c);
		return _os;
	}
}

const char* PEGParser::SymbolName(PEGParser::SymbolType _type)
{
	switch (_type)
	{
		case SymbolType_AND: return "AND";
		case SymbolType_CLOSE: return "CLOSE";
		case SymbolType_Char: return "Char";
		case SymbolType_Class: return "Class";
		case SymbolType_Comment: return "Comment";
		case SymbolType_DOT: return "DOT";
		case SymbolType_Definition: return "Definition";
		case SymbolType_EndOfFile: return "EndOfFile";
		case SymbolType_EndOfLine: return "EndOfLine";
		case SymbolType_Expression: return "Expression";
		case SymbolType_Grammar: return "Grammar";
		case SymbolType_Identifier: return "Identifier";
		case SymbolType_LEFTARROW: return "LEFTARROW";
		case SymbolType_Literal: return "Literal";
		case SymbolType_NOT: return "NOT";
		case SymbolType_OPEN: return "OPEN";
		case SymbolType_PLUS: return "PLUS";
		case SymbolType_Prefix: return "Prefix";
		case SymbolType_Primary: return "Primary";
		case SymbolType_QUESTION: return "QUESTION";
		case SymbolType_Range: return "Range";
		case SymbolType_SLASH: return "SLASH";
		case SymbolType_STAR: return "STAR";
		case SymbolType_Sequence: return "Sequence";
		case SymbolType_Space: return "Space";
		case SymbolType_Spacing: return "Spacing";
		case SymbolType_Suffix: return "Suffix";
		default: throw std::runtime_error(str(boost::format("Invalid Symbol Type: %1%") % _type));
	}
}

int PEGParser::Parser::SetEnd(SymbolType _type, const char* _pBegin, const char* _pEnd, int _complexity)
{
	if (_complexity > 32)
	{
		memoMap[_type][_pBegin] = _pEnd;
		return 1;
	}
	else
	{
		return _complexity;
	}
}

const char* PEGParser::Parser::Parse(SymbolType _type, const char* _pBegin, int& _complexity)
{
	int complexity = 0;
	const char* p = _pBegin;
	switch (_type)
	{
		case SymbolType_AND:
		{
			MemoMap::iterator i = memoMap[SymbolType_AND].find(_pBegin);
			if (i != memoMap[_type].end())
				return i->second;
			++complexity;
			if (*p == '&')
				++p;
			else
				p = 0;
			if (p)
			{
				p = Parse(SymbolType_Spacing, p, complexity);
			}
			_complexity += SetEnd(SymbolType_AND, _pBegin, p, complexity);
		  return p;
		}

		case SymbolType_CLOSE:
		{
			MemoMap::iterator i = memoMap[SymbolType_CLOSE].find(_pBegin);
			if (i != memoMap[_type].end())
				return i->second;
			++complexity;
			if (*p == ')')
				++p;
			else
				p = 0;
			if (p)
			{
				p = Parse(SymbolType_Spacing, p, complexity);
			}
			_complexity += SetEnd(SymbolType_CLOSE, _pBegin, p, complexity);
		  return p;
		}

		case SymbolType_Char:
		{
			MemoMap::iterator i = memoMap[SymbolType_Char].find(_pBegin);
			if (i != memoMap[_type].end())
				return i->second;
			const char* b = p;
			++complexity;
			if (*p == '\\')
				++p;
			else
				p = 0;
			if (p)
			{
				const char* b2 = p;
				++complexity;
				if (*p == 'n')
					++p;
				else
					p = 0;
				if (!p)
				{
					p = b2;
					++complexity;
					if (*p == 'r')
						++p;
					else
						p = 0;
					if (!p)
					{
						p = b2;
						++complexity;
						if (*p == 't')
							++p;
						else
							p = 0;
						if (!p)
						{
							p = b2;
							++complexity;
							if (*p == '\'')
								++p;
							else
								p = 0;
							if (!p)
							{
								p = b2;
								++complexity;
								if (*p == '\"')
									++p;
								else
									p = 0;
								if (!p)
								{
									p = b2;
									++complexity;
									if (*p == '[')
										++p;
									else
										p = 0;
									if (!p)
									{
										p = b2;
										++complexity;
										if (*p == ']')
											++p;
										else
											p = 0;
										if (!p)
										{
											p = b2;
											++complexity;
											if (*p == '\\')
												++p;
											else
												p = 0;
											if (!p)
											{
												p = b2;
												++complexity;
												if (*p >= '1' && *p <= '9')
													++p;
												else
													p = 0;
												if (p)
												{
													for (;;)
													{
														const char* b3 = p;
														++complexity;
														if (*p >= '0' && *p <= '9')
															++p;
														else
															p = 0;
														if (!p)
														{
															p = b3;
															break;
														}
													}
												}
											}
										}
									}
								}
							}
						}
					}
				}
			}
			if (!p)
			{
				p = b;
				++complexity;
				if (*p == '\\')
					++p;
				else
					p = 0;
				if (p) p = 0; else p = b;
				if (p)
				{
					++complexity;
					if (*p != 0)
						++p;
					else
						p = 0;
				}
			}
			_complexity += SetEnd(SymbolType_Char, _pBegin, p, complexity);
		  return p;
		}

		case SymbolType_Class:
		{
			MemoMap::iterator i = memoMap[SymbolType_Class].find(_pBegin);
			if (i != memoMap[_type].end())
				return i->second;
			++complexity;
			if (*p == '[')
				++p;
			else
				p = 0;
			if (p)
			{
				for (;;)
				{
					const char* b = p;
					++complexity;
					if (*p == ']')
						++p;
					else
						p = 0;
					if (p) p = 0; else p = b;
					if (p)
					{
						p = Parse(SymbolType_Range, p, complexity);
					}
					if (!p)
					{
						p = b;
						break;
					}
				}
				if (p)
				{
					++complexity;
					if (*p == ']')
						++p;
					else
						p = 0;
					if (p)
					{
						p = Parse(SymbolType_Spacing, p, complexity);
					}
				}
			}
			_complexity += SetEnd(SymbolType_Class, _pBegin, p, complexity);
		  return p;
		}

		case SymbolType_Comment:
		{
			MemoMap::iterator i = memoMap[SymbolType_Comment].find(_pBegin);
			if (i != memoMap[_type].end())
				return i->second;
			++complexity;
			if (*p == '#')
				++p;
			else
				p = 0;
			if (p)
			{
				for (;;)
				{
					const char* b = p;
					p = Parse(SymbolType_EndOfLine, p, complexity);
					if (p) p = 0; else p = b;
					if (p)
					{
						++complexity;
						if (*p != 0)
							++p;
						else
							p = 0;
					}
					if (!p)
					{
						p = b;
						break;
					}
				}
				if (p)
				{
					p = Parse(SymbolType_EndOfLine, p, complexity);
				}
			}
			_complexity += SetEnd(SymbolType_Comment, _pBegin, p, complexity);
		  return p;
		}

		case SymbolType_DOT:
		{
			MemoMap::iterator i = memoMap[SymbolType_DOT].find(_pBegin);
			if (i != memoMap[_type].end())
				return i->second;
			++complexity;
			if (*p == '.')
				++p;
			else
				p = 0;
			if (p)
			{
				p = Parse(SymbolType_Spacing, p, complexity);
			}
			_complexity += SetEnd(SymbolType_DOT, _pBegin, p, complexity);
		  return p;
		}

		case SymbolType_Definition:
		{
			MemoMap::iterator i = memoMap[SymbolType_Definition].find(_pBegin);
			if (i != memoMap[_type].end())
				return i->second;
			p = Parse(SymbolType_Identifier, p, complexity);
			if (p)
			{
				p = Parse(SymbolType_Spacing, p, complexity);
				if (p)
				{
					p = Parse(SymbolType_LEFTARROW, p, complexity);
					if (p)
					{
						p = Parse(SymbolType_Expression, p, complexity);
					}
				}
			}
			_complexity += SetEnd(SymbolType_Definition, _pBegin, p, complexity);
		  return p;
		}

		case SymbolType_EndOfFile:
		{
			MemoMap::iterator i = memoMap[SymbolType_EndOfFile].find(_pBegin);
			if (i != memoMap[_type].end())
				return i->second;
			const char* b = p;
			++complexity;
			if (*p != 0)
				++p;
			else
				p = 0;
			if (p) p = 0; else p = b;
			_complexity += SetEnd(SymbolType_EndOfFile, _pBegin, p, complexity);
		  return p;
		}

		case SymbolType_EndOfLine:
		{
			MemoMap::iterator i = memoMap[SymbolType_EndOfLine].find(_pBegin);
			if (i != memoMap[_type].end())
				return i->second;
			const char* b = p;
			++complexity;
			if (*p == '\r')
				++p;
			else
				p = 0;
			if (p)
			{
				++complexity;
				if (*p == '\n')
					++p;
				else
					p = 0;
			}
			if (!p)
			{
				p = b;
				++complexity;
				if (*p == '\n')
					++p;
				else
					p = 0;
				if (!p)
				{
					p = b;
					++complexity;
					if (*p == '\r')
						++p;
					else
						p = 0;
				}
			}
			_complexity += SetEnd(SymbolType_EndOfLine, _pBegin, p, complexity);
		  return p;
		}

		case SymbolType_Expression:
		{
			MemoMap::iterator i = memoMap[SymbolType_Expression].find(_pBegin);
			if (i != memoMap[_type].end())
				return i->second;
			p = Parse(SymbolType_Sequence, p, complexity);
			if (p)
			{
				for (;;)
				{
					const char* b = p;
					p = Parse(SymbolType_SLASH, p, complexity);
					if (p)
					{
						p = Parse(SymbolType_Sequence, p, complexity);
					}
					if (!p)
					{
						p = b;
						break;
					}
				}
			}
			_complexity += SetEnd(SymbolType_Expression, _pBegin, p, complexity);
		  return p;
		}

		case SymbolType_Grammar:
		{
			MemoMap::iterator i = memoMap[SymbolType_Grammar].find(_pBegin);
			if (i != memoMap[_type].end())
				return i->second;
			p = Parse(SymbolType_Spacing, p, complexity);
			if (p)
			{
				p = Parse(SymbolType_Definition, p, complexity);
				if (p)
				{
					for (;;)
					{
						const char* b = p;
						p = Parse(SymbolType_Definition, p, complexity);
						if (!p)
						{
							p = b;
							break;
						}
					}
					if (p)
					{
						p = Parse(SymbolType_EndOfFile, p, complexity);
					}
				}
			}
			_complexity += SetEnd(SymbolType_Grammar, _pBegin, p, complexity);
		  return p;
		}

		case SymbolType_Identifier:
		{
			MemoMap::iterator i = memoMap[SymbolType_Identifier].find(_pBegin);
			if (i != memoMap[_type].end())
				return i->second;
			const char* b = p;
			++complexity;
			if (*p >= 'a' && *p <= 'z')
				++p;
			else
				p = 0;
			if (!p)
			{
				p = b;
				++complexity;
				if (*p >= 'A' && *p <= 'Z')
					++p;
				else
					p = 0;
				if (!p)
				{
					p = b;
					++complexity;
					if (*p == '_')
						++p;
					else
						p = 0;
				}
			}
			if (p)
			{
				for (;;)
				{
					const char* b2 = p;
					++complexity;
					if (*p >= 'a' && *p <= 'z')
						++p;
					else
						p = 0;
					if (!p)
					{
						p = b2;
						++complexity;
						if (*p >= 'A' && *p <= 'Z')
							++p;
						else
							p = 0;
						if (!p)
						{
							p = b2;
							++complexity;
							if (*p >= '0' && *p <= '9')
								++p;
							else
								p = 0;
							if (!p)
							{
								p = b2;
								++complexity;
								if (*p == '_')
									++p;
								else
									p = 0;
							}
						}
					}
					if (!p)
					{
						p = b2;
						break;
					}
				}
			}
			_complexity += SetEnd(SymbolType_Identifier, _pBegin, p, complexity);
		  return p;
		}

		case SymbolType_LEFTARROW:
		{
			MemoMap::iterator i = memoMap[SymbolType_LEFTARROW].find(_pBegin);
			if (i != memoMap[_type].end())
				return i->second;
			++complexity;
			if (*p == '<')
				++p;
			else
				p = 0;
			if (p)
			{
				const char* b = p;
				++complexity;
				if (*p == '-')
					++p;
				else
					p = 0;
				if (!p)
				{
					p = b;
					++complexity;
					if (*p == '=')
						++p;
					else
						p = 0;
					if (!p)
					{
						p = b;
						++complexity;
						if (*p == '<')
							++p;
						else
							p = 0;
					}
				}
				if (p)
				{
					p = Parse(SymbolType_Spacing, p, complexity);
				}
			}
			_complexity += SetEnd(SymbolType_LEFTARROW, _pBegin, p, complexity);
		  return p;
		}

		case SymbolType_Literal:
		{
			MemoMap::iterator i = memoMap[SymbolType_Literal].find(_pBegin);
			if (i != memoMap[_type].end())
				return i->second;
			const char* b = p;
			++complexity;
			if (*p == '\'')
				++p;
			else
				p = 0;
			if (p)
			{
				for (;;)
				{
					const char* b2 = p;
					++complexity;
					if (*p == '\'')
						++p;
					else
						p = 0;
					if (p) p = 0; else p = b2;
					if (p)
					{
						p = Parse(SymbolType_Char, p, complexity);
					}
					if (!p)
					{
						p = b2;
						break;
					}
				}
				if (p)
				{
					++complexity;
					if (*p == '\'')
						++p;
					else
						p = 0;
					if (p)
					{
						p = Parse(SymbolType_Spacing, p, complexity);
					}
				}
			}
			if (!p)
			{
				p = b;
				++complexity;
				if (*p == '\"')
					++p;
				else
					p = 0;
				if (p)
				{
					for (;;)
					{
						const char* b3 = p;
						++complexity;
						if (*p == '\"')
							++p;
						else
							p = 0;
						if (p) p = 0; else p = b3;
						if (p)
						{
							p = Parse(SymbolType_Char, p, complexity);
						}
						if (!p)
						{
							p = b3;
							break;
						}
					}
					if (p)
					{
						++complexity;
						if (*p == '\"')
							++p;
						else
							p = 0;
						if (p)
						{
							p = Parse(SymbolType_Spacing, p, complexity);
						}
					}
				}
			}
			_complexity += SetEnd(SymbolType_Literal, _pBegin, p, complexity);
		  return p;
		}

		case SymbolType_NOT:
		{
			MemoMap::iterator i = memoMap[SymbolType_NOT].find(_pBegin);
			if (i != memoMap[_type].end())
				return i->second;
			++complexity;
			if (*p == '!')
				++p;
			else
				p = 0;
			if (p)
			{
				p = Parse(SymbolType_Spacing, p, complexity);
			}
			_complexity += SetEnd(SymbolType_NOT, _pBegin, p, complexity);
		  return p;
		}

		case SymbolType_OPEN:
		{
			MemoMap::iterator i = memoMap[SymbolType_OPEN].find(_pBegin);
			if (i != memoMap[_type].end())
				return i->second;
			++complexity;
			if (*p == '(')
				++p;
			else
				p = 0;
			if (p)
			{
				p = Parse(SymbolType_Spacing, p, complexity);
			}
			_complexity += SetEnd(SymbolType_OPEN, _pBegin, p, complexity);
		  return p;
		}

		case SymbolType_PLUS:
		{
			MemoMap::iterator i = memoMap[SymbolType_PLUS].find(_pBegin);
			if (i != memoMap[_type].end())
				return i->second;
			++complexity;
			if (*p == '+')
				++p;
			else
				p = 0;
			if (p)
			{
				p = Parse(SymbolType_Spacing, p, complexity);
			}
			_complexity += SetEnd(SymbolType_PLUS, _pBegin, p, complexity);
		  return p;
		}

		case SymbolType_Prefix:
		{
			MemoMap::iterator i = memoMap[SymbolType_Prefix].find(_pBegin);
			if (i != memoMap[_type].end())
				return i->second;
			const char* b = p;
			p = Parse(SymbolType_AND, p, complexity);
			if (!p)
			{
				p = b;
				p = Parse(SymbolType_NOT, p, complexity);
				if (!p)
				{
					p = b;
				}
			}
			if (p)
			{
				p = Parse(SymbolType_Suffix, p, complexity);
			}
			_complexity += SetEnd(SymbolType_Prefix, _pBegin, p, complexity);
		  return p;
		}

		case SymbolType_Primary:
		{
			MemoMap::iterator i = memoMap[SymbolType_Primary].find(_pBegin);
			if (i != memoMap[_type].end())
				return i->second;
			const char* b = p;
			p = Parse(SymbolType_Identifier, p, complexity);
			if (p)
			{
				p = Parse(SymbolType_Spacing, p, complexity);
				if (p)
				{
					const char* b2 = p;
					p = Parse(SymbolType_LEFTARROW, p, complexity);
					if (p) p = 0; else p = b2;
				}
			}
			if (!p)
			{
				p = b;
				p = Parse(SymbolType_OPEN, p, complexity);
				if (p)
				{
					p = Parse(SymbolType_Expression, p, complexity);
					if (p)
					{
						p = Parse(SymbolType_CLOSE, p, complexity);
					}
				}
				if (!p)
				{
					p = b;
					p = Parse(SymbolType_Literal, p, complexity);
					if (!p)
					{
						p = b;
						p = Parse(SymbolType_Class, p, complexity);
						if (!p)
						{
							p = b;
							p = Parse(SymbolType_DOT, p, complexity);
						}
					}
				}
			}
			_complexity += SetEnd(SymbolType_Primary, _pBegin, p, complexity);
		  return p;
		}

		case SymbolType_QUESTION:
		{
			MemoMap::iterator i = memoMap[SymbolType_QUESTION].find(_pBegin);
			if (i != memoMap[_type].end())
				return i->second;
			++complexity;
			if (*p == '?')
				++p;
			else
				p = 0;
			if (p)
			{
				p = Parse(SymbolType_Spacing, p, complexity);
			}
			_complexity += SetEnd(SymbolType_QUESTION, _pBegin, p, complexity);
		  return p;
		}

		case SymbolType_Range:
		{
			MemoMap::iterator i = memoMap[SymbolType_Range].find(_pBegin);
			if (i != memoMap[_type].end())
				return i->second;
			p = Parse(SymbolType_Char, p, complexity);
			if (p)
			{
				const char* b = p;
				++complexity;
				if (*p == '-')
					++p;
				else
					p = 0;
				if (p)
				{
					p = Parse(SymbolType_Char, p, complexity);
				}
				if (!p)
				{
					p = b;
				}
			}
			_complexity += SetEnd(SymbolType_Range, _pBegin, p, complexity);
		  return p;
		}

		case SymbolType_SLASH:
		{
			MemoMap::iterator i = memoMap[SymbolType_SLASH].find(_pBegin);
			if (i != memoMap[_type].end())
				return i->second;
			++complexity;
			if (*p == '/')
				++p;
			else
				p = 0;
			if (p)
			{
				p = Parse(SymbolType_Spacing, p, complexity);
			}
			_complexity += SetEnd(SymbolType_SLASH, _pBegin, p, complexity);
		  return p;
		}

		case SymbolType_STAR:
		{
			MemoMap::iterator i = memoMap[SymbolType_STAR].find(_pBegin);
			if (i != memoMap[_type].end())
				return i->second;
			++complexity;
			if (*p == '*')
				++p;
			else
				p = 0;
			if (p)
			{
				p = Parse(SymbolType_Spacing, p, complexity);
			}
			_complexity += SetEnd(SymbolType_STAR, _pBegin, p, complexity);
		  return p;
		}

		case SymbolType_Sequence:
		{
			MemoMap::iterator i = memoMap[SymbolType_Sequence].find(_pBegin);
			if (i != memoMap[_type].end())
				return i->second;
			for (;;)
			{
				const char* b = p;
				p = Parse(SymbolType_Prefix, p, complexity);
				if (!p)
				{
					p = b;
					break;
				}
			}
			_complexity += SetEnd(SymbolType_Sequence, _pBegin, p, complexity);
		  return p;
		}

		case SymbolType_Space:
		{
			MemoMap::iterator i = memoMap[SymbolType_Space].find(_pBegin);
			if (i != memoMap[_type].end())
				return i->second;
			const char* b = p;
			++complexity;
			if (*p == ' ')
				++p;
			else
				p = 0;
			if (!p)
			{
				p = b;
				++complexity;
				if (*p == '\t')
					++p;
				else
					p = 0;
				if (!p)
				{
					p = b;
					p = Parse(SymbolType_EndOfLine, p, complexity);
				}
			}
			_complexity += SetEnd(SymbolType_Space, _pBegin, p, complexity);
		  return p;
		}

		case SymbolType_Spacing:
		{
			MemoMap::iterator i = memoMap[SymbolType_Spacing].find(_pBegin);
			if (i != memoMap[_type].end())
				return i->second;
			for (;;)
			{
				const char* b = p;
				p = Parse(SymbolType_Space, p, complexity);
				if (!p)
				{
					p = b;
					p = Parse(SymbolType_Comment, p, complexity);
				}
				if (!p)
				{
					p = b;
					break;
				}
			}
			_complexity += SetEnd(SymbolType_Spacing, _pBegin, p, complexity);
		  return p;
		}

		case SymbolType_Suffix:
		{
			MemoMap::iterator i = memoMap[SymbolType_Suffix].find(_pBegin);
			if (i != memoMap[_type].end())
				return i->second;
			p = Parse(SymbolType_Primary, p, complexity);
			if (p)
			{
				const char* b = p;
				p = Parse(SymbolType_QUESTION, p, complexity);
				if (!p)
				{
					p = b;
					p = Parse(SymbolType_STAR, p, complexity);
					if (!p)
					{
						p = b;
						p = Parse(SymbolType_PLUS, p, complexity);
						if (!p)
						{
							p = b;
						}
					}
				}
			}
			_complexity += SetEnd(SymbolType_Suffix, _pBegin, p, complexity);
		  return p;
		}

		default:
			assert(false);
			return 0;
	}
}

const char* PEGParser::Parser::Traverse(PEGParser::SymbolType _type, const char* _pBegin, PEGParser::Symbols& v, int& _complexity)
{
	int complexity = 0;
	const char* p = _pBegin;
	switch (_type)
	{
		case SymbolType_Class:
		{
			MemoMap::iterator i = memoMap[SymbolType_Class].find(_pBegin);
			if (i != memoMap[_type].end() && i->second == 0)
				return 0;
			++complexity;
			if (*p == '[')
				++p;
			else
				p = 0;
			if (p)
			{
				for (;;)
				{
					const char* b = p;
					size_t s = v.size();
					++complexity;
					if (*p == ']')
						++p;
					else
						p = 0;
					if (p) p = 0; else p = b;
					if (p)
					{
						p = Visit(SymbolType_Range, p, v);
					}
					if (!p)
					{
						p = b;
						v.erase(v.begin() + s, v.end());
						break;
					}
				}
				if (p)
				{
					++complexity;
					if (*p == ']')
						++p;
					else
						p = 0;
					if (p)
					{
						p = Parse(SymbolType_Spacing, p, complexity);
					}
				}
			}
			_complexity += SetEnd(SymbolType_Class, _pBegin, p, complexity);
			return p;
		}

		case SymbolType_Definition:
		{
			MemoMap::iterator i = memoMap[SymbolType_Definition].find(_pBegin);
			if (i != memoMap[_type].end() && i->second == 0)
				return 0;
			p = Visit(SymbolType_Identifier, p, v);
			if (p)
			{
				p = Parse(SymbolType_Spacing, p, complexity);
				if (p)
				{
					p = Visit(SymbolType_LEFTARROW, p, v);
					if (p)
					{
						p = Visit(SymbolType_Expression, p, v);
					}
				}
			}
			_complexity += SetEnd(SymbolType_Definition, _pBegin, p, complexity);
			return p;
		}

		case SymbolType_Expression:
		{
			MemoMap::iterator i = memoMap[SymbolType_Expression].find(_pBegin);
			if (i != memoMap[_type].end() && i->second == 0)
				return 0;
			p = Visit(SymbolType_Sequence, p, v);
			if (p)
			{
				for (;;)
				{
					const char* b = p;
					size_t s = v.size();
					p = Parse(SymbolType_SLASH, p, complexity);
					if (p)
					{
						p = Visit(SymbolType_Sequence, p, v);
					}
					if (!p)
					{
						p = b;
						v.erase(v.begin() + s, v.end());
						break;
					}
				}
			}
			_complexity += SetEnd(SymbolType_Expression, _pBegin, p, complexity);
			return p;
		}

		case SymbolType_Grammar:
		{
			MemoMap::iterator i = memoMap[SymbolType_Grammar].find(_pBegin);
			if (i != memoMap[_type].end() && i->second == 0)
				return 0;
			p = Parse(SymbolType_Spacing, p, complexity);
			if (p)
			{
				p = Visit(SymbolType_Definition, p, v);
				if (p)
				{
					for (;;)
					{
						const char* b = p;
						size_t s = v.size();
						p = Visit(SymbolType_Definition, p, v);
						if (!p)
						{
							p = b;
							v.erase(v.begin() + s, v.end());
							break;
						}
					}
					if (p)
					{
						p = Parse(SymbolType_EndOfFile, p, complexity);
					}
				}
			}
			_complexity += SetEnd(SymbolType_Grammar, _pBegin, p, complexity);
			return p;
		}

		case SymbolType_Literal:
		{
			MemoMap::iterator i = memoMap[SymbolType_Literal].find(_pBegin);
			if (i != memoMap[_type].end() && i->second == 0)
				return 0;
			const char* b = p;
			size_t s = v.size();
			++complexity;
			if (*p == '\'')
				++p;
			else
				p = 0;
			if (p)
			{
				for (;;)
				{
					const char* b2 = p;
					size_t s2 = v.size();
					++complexity;
					if (*p == '\'')
						++p;
					else
						p = 0;
					if (p) p = 0; else p = b2;
					if (p)
					{
						p = Visit(SymbolType_Char, p, v);
					}
					if (!p)
					{
						p = b2;
						v.erase(v.begin() + s2, v.end());
						break;
					}
				}
				if (p)
				{
					++complexity;
					if (*p == '\'')
						++p;
					else
						p = 0;
					if (p)
					{
						p = Parse(SymbolType_Spacing, p, complexity);
					}
				}
			}
			if (!p)
			{
				p = b;
				v.erase(v.begin() + s, v.end());
				++complexity;
				if (*p == '\"')
					++p;
				else
					p = 0;
				if (p)
				{
					for (;;)
					{
						const char* b3 = p;
						size_t s3 = v.size();
						++complexity;
						if (*p == '\"')
							++p;
						else
							p = 0;
						if (p) p = 0; else p = b3;
						if (p)
						{
							p = Visit(SymbolType_Char, p, v);
						}
						if (!p)
						{
							p = b3;
							v.erase(v.begin() + s3, v.end());
							break;
						}
					}
					if (p)
					{
						++complexity;
						if (*p == '\"')
							++p;
						else
							p = 0;
						if (p)
						{
							p = Parse(SymbolType_Spacing, p, complexity);
						}
					}
				}
			}
			_complexity += SetEnd(SymbolType_Literal, _pBegin, p, complexity);
			return p;
		}

		case SymbolType_Prefix:
		{
			MemoMap::iterator i = memoMap[SymbolType_Prefix].find(_pBegin);
			if (i != memoMap[_type].end() && i->second == 0)
				return 0;
			const char* b = p;
			p = Parse(SymbolType_AND, p, complexity);
			if (!p)
			{
				p = b;
				p = Parse(SymbolType_NOT, p, complexity);
				if (!p)
				{
					p = b;
				}
			}
			if (p)
			{
				p = Visit(SymbolType_Suffix, p, v);
			}
			_complexity += SetEnd(SymbolType_Prefix, _pBegin, p, complexity);
			return p;
		}

		case SymbolType_Primary:
		{
			MemoMap::iterator i = memoMap[SymbolType_Primary].find(_pBegin);
			if (i != memoMap[_type].end() && i->second == 0)
				return 0;
			const char* b = p;
			size_t s = v.size();
			p = Visit(SymbolType_Identifier, p, v);
			if (p)
			{
				p = Parse(SymbolType_Spacing, p, complexity);
				if (p)
				{
					const char* b2 = p;
					p = Parse(SymbolType_LEFTARROW, p, complexity);
					if (p) p = 0; else p = b2;
				}
			}
			if (!p)
			{
				p = b;
				v.erase(v.begin() + s, v.end());
				p = Parse(SymbolType_OPEN, p, complexity);
				if (p)
				{
					p = Visit(SymbolType_Expression, p, v);
					if (p)
					{
						p = Parse(SymbolType_CLOSE, p, complexity);
					}
				}
				if (!p)
				{
					p = b;
					v.erase(v.begin() + s, v.end());
					p = Visit(SymbolType_Literal, p, v);
					if (!p)
					{
						p = b;
						v.erase(v.begin() + s, v.end());
						p = Visit(SymbolType_Class, p, v);
						if (!p)
						{
							p = b;
							v.erase(v.begin() + s, v.end());
							p = Parse(SymbolType_DOT, p, complexity);
						}
					}
				}
			}
			_complexity += SetEnd(SymbolType_Primary, _pBegin, p, complexity);
			return p;
		}

		case SymbolType_Range:
		{
			MemoMap::iterator i = memoMap[SymbolType_Range].find(_pBegin);
			if (i != memoMap[_type].end() && i->second == 0)
				return 0;
			p = Visit(SymbolType_Char, p, v);
			if (p)
			{
				const char* b = p;
				size_t s = v.size();
				++complexity;
				if (*p == '-')
					++p;
				else
					p = 0;
				if (p)
				{
					p = Visit(SymbolType_Char, p, v);
				}
				if (!p)
				{
					p = b;
					v.erase(v.begin() + s, v.end());
				}
			}
			_complexity += SetEnd(SymbolType_Range, _pBegin, p, complexity);
			return p;
		}

		case SymbolType_Sequence:
		{
			MemoMap::iterator i = memoMap[SymbolType_Sequence].find(_pBegin);
			if (i != memoMap[_type].end() && i->second == 0)
				return 0;
			for (;;)
			{
				const char* b = p;
				size_t s = v.size();
				p = Visit(SymbolType_Prefix, p, v);
				if (!p)
				{
					p = b;
					v.erase(v.begin() + s, v.end());
					break;
				}
			}
			_complexity += SetEnd(SymbolType_Sequence, _pBegin, p, complexity);
			return p;
		}

		case SymbolType_Suffix:
		{
			MemoMap::iterator i = memoMap[SymbolType_Suffix].find(_pBegin);
			if (i != memoMap[_type].end() && i->second == 0)
				return 0;
			p = Visit(SymbolType_Primary, p, v);
			if (p)
			{
				const char* b = p;
				p = Parse(SymbolType_QUESTION, p, complexity);
				if (!p)
				{
					p = b;
					p = Parse(SymbolType_STAR, p, complexity);
					if (!p)
					{
						p = b;
						p = Parse(SymbolType_PLUS, p, complexity);
						if (!p)
						{
							p = b;
						}
					}
				}
			}
			_complexity += SetEnd(SymbolType_Suffix, _pBegin, p, complexity);
			return p;
		}

		case SymbolType_AND:
		case SymbolType_CLOSE:
		case SymbolType_Char:
		case SymbolType_Comment:
		case SymbolType_DOT:
		case SymbolType_EndOfFile:
		case SymbolType_EndOfLine:
		case SymbolType_Identifier:
		case SymbolType_LEFTARROW:
		case SymbolType_NOT:
		case SymbolType_OPEN:
		case SymbolType_PLUS:
		case SymbolType_QUESTION:
		case SymbolType_SLASH:
		case SymbolType_STAR:
		case SymbolType_Space:
		case SymbolType_Spacing:
			return Parse(_type, p, _complexity);

		default:
			assert(false);
			return 0;
	}
}

void PEGParser::Parser::Print(std::ostream& _os, PEGParser::SymbolType _type, const char* _pNode, int _tabs, int _maxLineSize)
{
	Symbols children;
	int complexity = 0;
	const char* pEnd = Traverse(_type, _pNode, children, complexity);
	if (!pEnd)
		throw std::runtime_error(str(boost::format("Parsing Failed for \"%1%\"") % SymbolName(_type)));

	int tabCount = _tabs;
	while (tabCount--)
		_os << "    ";

	_os << SymbolName(_type) << ": \"";

	size_t lineSize = 0;
	for (const char* p = _pNode; p != pEnd; ++p)
	{
		_os << EscapeChar(*p);
		if (++lineSize >= _maxLineSize)
		{
			_os << "...";
			break;
		}
	}

	_os << "\"\n";

	for (Symbols::iterator i = children.begin(), iEnd = children.end(); i != iEnd; ++i)
		Print(_os, i->first, i->second, _tabs + 1, _maxLineSize);
//*
	if (_tabs == 0)
	{
		for (size_t k = 0; k < SymbolTypeCount; ++k)
		{
			_os << SymbolName(SymbolType(k)) << "Memo Count: " << memoMap[k].size() << "\n";
		}
	}
//*/
}

const char* PEGParser::Parser::Visit(PEGParser::SymbolType _type, const char* _p, PEGParser::Symbols& _v)
{
	int complexity = 0;
	const char* pEnd = Parse(_type, _p, complexity);
	if (pEnd)
		_v.push_back(Symbol(_type, _p));
	return pEnd;
}

PEGParser::Iterator::Iterator(PEGParser::SymbolType _type, const char* _pNode)
:	mType(_type)
,	mpNode(_pNode)
, mpSiblings(new Symbols)
, mpParser(new Parser)
{
	if (mpNode && End())
		mpSiblings->push_back(Symbol(mType, mpNode));

	miCurrent = mpSiblings->begin();				
}

PEGParser::Iterator::Iterator(const PEGParser::Iterator& _iOther)
: mType(_iOther.mType)
,	mpNode(_iOther.mpNode)
, mpSiblings(_iOther.mpSiblings)
, miCurrent(_iOther.miCurrent)
,	mpParser(_iOther.mpParser)
{
}

PEGParser::Iterator::operator bool() const
{
	return mpNode != 0;
}

PEGParser::Iterator& PEGParser::Iterator::operator++()
{
	mpChildren.reset();
	GoToNext(mType);
	return *this;
}

PEGParser::SymbolType PEGParser::Iterator::GetType() const
{
	return mType;
}

const char* PEGParser::Iterator::Begin() const
{
	assert(mpNode);
	return mpNode;
}

const char* PEGParser::Iterator::End() const
{
	assert(mpNode);
	int complexity = 0;
	return mpParser->Parse(mType, mpNode, complexity);
}

PEGParser::Iterator PEGParser::Iterator::GetChild(PEGParser::SymbolType _childT)
{
	assert(mpNode != 0);
	return Iterator(mpParser, GetChildren(), _childT);
}

PEGParser::Iterator PEGParser::Iterator::GetNext(PEGParser::SymbolType _childT)
{
	assert(mpNode != 0);
	return Iterator(*this, _childT);
}

void PEGParser::Iterator::Print(std::ostream& _os, int _tabs, int _maxLineSize)
{
	mpParser->Print(_os, mType, mpNode, _tabs, _maxLineSize);
}

PEGParser::Iterator::Iterator(boost::shared_ptr<PEGParser::Parser> _pParser, boost::shared_ptr<PEGParser::Symbols> _pSiblings, PEGParser::SymbolType _childType)
: mType(_childType)
, mpSiblings(_pSiblings)
, miCurrent(_pSiblings->begin())
,	mpParser(_pParser)
{
	SkipSiblingsWithWrongType(_childType);
}

PEGParser::Iterator::Iterator(const PEGParser::Iterator& _iOther, PEGParser::SymbolType _childType)
: mType(_childType)
,	mpSiblings(_iOther.mpSiblings)
,	miCurrent(_iOther.miCurrent)
,	mpParser(_iOther.mpParser)
{
	SkipSiblingsWithWrongType(_childType);
}

void PEGParser::Iterator::GoToNext(PEGParser::SymbolType _childType)
{
	++miCurrent;
	SkipSiblingsWithWrongType(_childType);
}

void PEGParser::Iterator::SkipSiblingsWithWrongType(PEGParser::SymbolType _childType)
{
	Symbols::iterator iEnd = mpSiblings->end();
	while (miCurrent != iEnd && miCurrent->first != _childType)
		++miCurrent;
	mpNode = (miCurrent != iEnd) ? miCurrent->second : 0 ;
}

boost::shared_ptr<PEGParser::Symbols> PEGParser::Iterator::GetChildren()
{
	if (!mpChildren)
	{
		Symbols children;
		int complexity = 0;
		mpParser->Traverse(mType, mpNode, children, complexity);
		mpChildren.reset(new Symbols);
		mpChildren->swap(children);			
	}
	return mpChildren;
}

std::ostream& PEGParser::operator<<(std::ostream& _os, const PEGParser::Iterator& _i)
{
	if (_i)
	{
		for (const char *p = _i.Begin(), *pEnd = _i.End(); p != pEnd; ++p)
			_os.put(*p);
	}
	return _os;
}

