// This file was automatically generated by IPG on Mon Jul 18 23:08:35 2011
// (from /Users/alexk7/ipg/build/xcode/../../src/peg/peg.peg)
// DO NOT EDIT!
#include <cassert>
#include <stdexcept>
#include <ostream>
#include <sstream>
#include <iomanip>
#include <vector>
#include <boost/shared_ptr.hpp>
#include <boost/unordered_map.hpp>

namespace PEGParser
{
	enum SymbolType
	{
		SymbolType_AND = 1,
		SymbolType_CLOSE = 2,
		SymbolType_Char = 3,
		SymbolType_Class = 4,
		SymbolType_Comment = 5,
		SymbolType_DOT = 6,
		SymbolType_Definition = 7,
		SymbolType_EndOfFile = 8,
		SymbolType_EndOfLine = 9,
		SymbolType_Expression = 10,
		SymbolType_Grammar = 11,
		SymbolType_Identifier = 12,
		SymbolType_LEFTARROW = 13,
		SymbolType_Literal = 14,
		SymbolType_NOT = 15,
		SymbolType_OPEN = 16,
		SymbolType_PLUS = 17,
		SymbolType_Prefix = 18,
		SymbolType_Primary = 19,
		SymbolType_QUESTION = 20,
		SymbolType_Range = 21,
		SymbolType_SLASH = 22,
		SymbolType_STAR = 23,
		SymbolType_Sequence = 24,
		SymbolType_Space = 25,
		SymbolType_Spacing = 26,
		SymbolType_Suffix = 27,
	};

	struct Node;
	typedef boost::unordered_map<SymbolType, Node*> SymbolTypeToPtr;

	struct Node
	{
		char value;
		SymbolTypeToPtr end;
	};

	typedef std::pair<SymbolType, Node*> PTNodeChild;
	typedef std::vector<PTNodeChild> PTNodeChildren;

	const char* SymbolName(SymbolType _type);

	class Parser
	{
	public:
		Node* Parse(SymbolType _type, Node* _symbol);
		Node* Traverse(SymbolType _type, Node* _symbol, PTNodeChildren& _children);
		void Print(std::ostream& _os, SymbolType _type, Node* _pNode, int _tabs = 0, int _maxLineSize = 100);

	private:
		Node* Visit(SymbolType _type, Node* _p, PTNodeChildren& _v);
	};

	class Iterator
	{
	public:
		Iterator(SymbolType _type, Node* _pNode = 0);
		Iterator(const Iterator& _iOther);
		operator bool() const;
		Iterator& operator++();
		SymbolType GetType() const;
		Node* Begin() const;
		Node* End() const;
		Iterator GetChild(SymbolType _childT);
		Iterator GetNext(SymbolType _childT);

	private:
		Iterator(boost::shared_ptr<Parser> _pParser, boost::shared_ptr<PTNodeChildren> _pSiblings, SymbolType _childType);
		Iterator(const Iterator& _iOther, SymbolType _childType);
		void GoToNext(SymbolType _childType);
		void SkipSiblingsWithWrongType(SymbolType _childType);
		boost::shared_ptr<PTNodeChildren> GetChildren();

		SymbolType mType;
		Node* mpNode;
		boost::shared_ptr<PTNodeChildren> mpSiblings;
		PTNodeChildren::iterator miCurrent;
		boost::shared_ptr<PTNodeChildren> mpChildren;
		boost::shared_ptr<Parser> mpParser;
	};

	std::ostream& operator<<(std::ostream& _os, const Iterator& _i);
}

namespace
{
	typedef PEGParser::SymbolTypeToPtr::value_type Memo;
	typedef PEGParser::SymbolTypeToPtr::iterator MemoIterator;
	typedef std::pair<PEGParser::SymbolTypeToPtr::iterator, bool> MemoInsertResult;

	struct EscapeChar
	{
		EscapeChar(char _c);
		char c;
	};

	EscapeChar::EscapeChar(char _c) : c(_c)
	{
	}

	std::ostream& operator<<(std::ostream& _os, EscapeChar _e)
	{
		char c = _e.c;
		switch (c)
		{
			case '\\': c = '\\'; break;
			case '\n': c = 'n';  break;
			case '\r': c = 'r';  break;
			case '\t': c = 't';  break;
			case '\'': c = '\''; break;
			case '\"': c = '\"'; break;
			default:
				_os.put(c);
				return _os;
		}
		_os.put('\\');
		_os.put(c);
		return _os;
	}
}

const char* PEGParser::SymbolName(PEGParser::SymbolType _type)
{
	switch (_type)
	{
		case SymbolType_AND: return "AND";
		case SymbolType_CLOSE: return "CLOSE";
		case SymbolType_Char: return "Char";
		case SymbolType_Class: return "Class";
		case SymbolType_Comment: return "Comment";
		case SymbolType_DOT: return "DOT";
		case SymbolType_Definition: return "Definition";
		case SymbolType_EndOfFile: return "EndOfFile";
		case SymbolType_EndOfLine: return "EndOfLine";
		case SymbolType_Expression: return "Expression";
		case SymbolType_Grammar: return "Grammar";
		case SymbolType_Identifier: return "Identifier";
		case SymbolType_LEFTARROW: return "LEFTARROW";
		case SymbolType_Literal: return "Literal";
		case SymbolType_NOT: return "NOT";
		case SymbolType_OPEN: return "OPEN";
		case SymbolType_PLUS: return "PLUS";
		case SymbolType_Prefix: return "Prefix";
		case SymbolType_Primary: return "Primary";
		case SymbolType_QUESTION: return "QUESTION";
		case SymbolType_Range: return "Range";
		case SymbolType_SLASH: return "SLASH";
		case SymbolType_STAR: return "STAR";
		case SymbolType_Sequence: return "Sequence";
		case SymbolType_Space: return "Space";
		case SymbolType_Spacing: return "Spacing";
		case SymbolType_Suffix: return "Suffix";
	}
}

PEGParser::Node* PEGParser::Parser::Parse(SymbolType _type, PEGParser::Node* p)
{
	switch (_type)
	{
		case SymbolType_AND:
		{
			if (p->value == '&') ++p; else p = 0;
			if (p)
			{
				p = Parse(SymbolType_Spacing, p);
			}
		  return p;
		}

		case SymbolType_CLOSE:
		{
			if (p->value == ')') ++p; else p = 0;
			if (p)
			{
				p = Parse(SymbolType_Spacing, p);
			}
		  return p;
		}

		case SymbolType_Char:
		{
			MemoInsertResult r = p->end.insert(Memo(SymbolType_Char, 0));
			if (!r.second) return r.first->second;
			Node* b = p;
			if (p->value == '\\') ++p; else p = 0;
			if (p)
			{
				Node* b2 = p;
				if (p->value == 'n') ++p; else p = 0;
				if (!p)
				{
					p = b2;
					if (p->value == 'r') ++p; else p = 0;
					if (!p)
					{
						p = b2;
						if (p->value == 't') ++p; else p = 0;
						if (!p)
						{
							p = b2;
							if (p->value == '\'') ++p; else p = 0;
							if (!p)
							{
								p = b2;
								if (p->value == '\"') ++p; else p = 0;
								if (!p)
								{
									p = b2;
									if (p->value == '[') ++p; else p = 0;
									if (!p)
									{
										p = b2;
										if (p->value == ']') ++p; else p = 0;
										if (!p)
										{
											p = b2;
											if (p->value == '\\') ++p; else p = 0;
											if (!p)
											{
												p = b2;
												if (p->value >= '1' && p->value <= '9') ++p; else p = 0;
												if (p)
												{
													for (;;)
													{
														Node* b3 = p;
														if (p->value >= '0' && p->value <= '9') ++p; else p = 0;
														if (!p)
														{
															p = b3;
															break;
														}
													}
												}
											}
										}
									}
								}
							}
						}
					}
				}
			}
			if (!p)
			{
				p = b;
				if (p->value == '\\') ++p; else p = 0;
				if (p) p = 0; else p = b;
				if (p)
				{
					if (p->value != 0) ++p; else p = 0;
				}
			}
			r.first->second = p;
		  return p;
		}

		case SymbolType_Class:
		{
			MemoInsertResult r = p->end.insert(Memo(SymbolType_Class, 0));
			if (!r.second) return r.first->second;
			if (p->value == '[') ++p; else p = 0;
			if (p)
			{
				for (;;)
				{
					Node* b = p;
					if (p->value == ']') ++p; else p = 0;
					if (p) p = 0; else p = b;
					if (p)
					{
						p = Parse(SymbolType_Range, p);
					}
					if (!p)
					{
						p = b;
						break;
					}
				}
				if (p)
				{
					if (p->value == ']') ++p; else p = 0;
					if (p)
					{
						p = Parse(SymbolType_Spacing, p);
					}
				}
			}
			r.first->second = p;
		  return p;
		}

		case SymbolType_Comment:
		{
			if (p->value == '#') ++p; else p = 0;
			if (p)
			{
				for (;;)
				{
					Node* b = p;
					p = Parse(SymbolType_EndOfLine, p);
					if (p) p = 0; else p = b;
					if (p)
					{
						if (p->value != 0) ++p; else p = 0;
					}
					if (!p)
					{
						p = b;
						break;
					}
				}
				if (p)
				{
					p = Parse(SymbolType_EndOfLine, p);
				}
			}
		  return p;
		}

		case SymbolType_DOT:
		{
			if (p->value == '.') ++p; else p = 0;
			if (p)
			{
				p = Parse(SymbolType_Spacing, p);
			}
		  return p;
		}

		case SymbolType_Definition:
		{
			MemoInsertResult r = p->end.insert(Memo(SymbolType_Definition, 0));
			if (!r.second) return r.first->second;
			p = Parse(SymbolType_Identifier, p);
			if (p)
			{
				p = Parse(SymbolType_Spacing, p);
				if (p)
				{
					p = Parse(SymbolType_LEFTARROW, p);
					if (p)
					{
						p = Parse(SymbolType_Expression, p);
					}
				}
			}
			r.first->second = p;
		  return p;
		}

		case SymbolType_EndOfFile:
		{
			Node* b = p;
			if (p->value != 0) ++p; else p = 0;
			if (p) p = 0; else p = b;
		  return p;
		}

		case SymbolType_EndOfLine:
		{
			Node* b = p;
			if (p->value == '\r') ++p; else p = 0;
			if (p)
			{
				if (p->value == '\n') ++p; else p = 0;
			}
			if (!p)
			{
				p = b;
				if (p->value == '\n') ++p; else p = 0;
				if (!p)
				{
					p = b;
					if (p->value == '\r') ++p; else p = 0;
				}
			}
		  return p;
		}

		case SymbolType_Expression:
		{
			MemoInsertResult r = p->end.insert(Memo(SymbolType_Expression, 0));
			if (!r.second) return r.first->second;
			p = Parse(SymbolType_Sequence, p);
			if (p)
			{
				for (;;)
				{
					Node* b = p;
					p = Parse(SymbolType_SLASH, p);
					if (p)
					{
						p = Parse(SymbolType_Sequence, p);
					}
					if (!p)
					{
						p = b;
						break;
					}
				}
			}
			r.first->second = p;
		  return p;
		}

		case SymbolType_Grammar:
		{
			MemoInsertResult r = p->end.insert(Memo(SymbolType_Grammar, 0));
			if (!r.second) return r.first->second;
			p = Parse(SymbolType_Spacing, p);
			if (p)
			{
				p = Parse(SymbolType_Definition, p);
				if (p)
				{
					for (;;)
					{
						Node* b = p;
						p = Parse(SymbolType_Definition, p);
						if (!p)
						{
							p = b;
							break;
						}
					}
					if (p)
					{
						p = Parse(SymbolType_EndOfFile, p);
					}
				}
			}
			r.first->second = p;
		  return p;
		}

		case SymbolType_Identifier:
		{
			MemoInsertResult r = p->end.insert(Memo(SymbolType_Identifier, 0));
			if (!r.second) return r.first->second;
			Node* b = p;
			if (p->value >= 'a' && p->value <= 'z') ++p; else p = 0;
			if (!p)
			{
				p = b;
				if (p->value >= 'A' && p->value <= 'Z') ++p; else p = 0;
				if (!p)
				{
					p = b;
					if (p->value == '_') ++p; else p = 0;
				}
			}
			if (p)
			{
				for (;;)
				{
					Node* b2 = p;
					if (p->value >= 'a' && p->value <= 'z') ++p; else p = 0;
					if (!p)
					{
						p = b2;
						if (p->value >= 'A' && p->value <= 'Z') ++p; else p = 0;
						if (!p)
						{
							p = b2;
							if (p->value >= '0' && p->value <= '9') ++p; else p = 0;
							if (!p)
							{
								p = b2;
								if (p->value == '_') ++p; else p = 0;
							}
						}
					}
					if (!p)
					{
						p = b2;
						break;
					}
				}
			}
			r.first->second = p;
		  return p;
		}

		case SymbolType_LEFTARROW:
		{
			MemoInsertResult r = p->end.insert(Memo(SymbolType_LEFTARROW, 0));
			if (!r.second) return r.first->second;
			if (p->value == '<') ++p; else p = 0;
			if (p)
			{
				Node* b = p;
				if (p->value == '-') ++p; else p = 0;
				if (!p)
				{
					p = b;
					if (p->value == '=') ++p; else p = 0;
					if (!p)
					{
						p = b;
						if (p->value == '<') ++p; else p = 0;
					}
				}
				if (p)
				{
					p = Parse(SymbolType_Spacing, p);
				}
			}
			r.first->second = p;
		  return p;
		}

		case SymbolType_Literal:
		{
			MemoInsertResult r = p->end.insert(Memo(SymbolType_Literal, 0));
			if (!r.second) return r.first->second;
			Node* b = p;
			if (p->value == '\'') ++p; else p = 0;
			if (p)
			{
				for (;;)
				{
					Node* b2 = p;
					if (p->value == '\'') ++p; else p = 0;
					if (p) p = 0; else p = b2;
					if (p)
					{
						p = Parse(SymbolType_Char, p);
					}
					if (!p)
					{
						p = b2;
						break;
					}
				}
				if (p)
				{
					if (p->value == '\'') ++p; else p = 0;
					if (p)
					{
						p = Parse(SymbolType_Spacing, p);
					}
				}
			}
			if (!p)
			{
				p = b;
				if (p->value == '\"') ++p; else p = 0;
				if (p)
				{
					for (;;)
					{
						Node* b3 = p;
						if (p->value == '\"') ++p; else p = 0;
						if (p) p = 0; else p = b3;
						if (p)
						{
							p = Parse(SymbolType_Char, p);
						}
						if (!p)
						{
							p = b3;
							break;
						}
					}
					if (p)
					{
						if (p->value == '\"') ++p; else p = 0;
						if (p)
						{
							p = Parse(SymbolType_Spacing, p);
						}
					}
				}
			}
			r.first->second = p;
		  return p;
		}

		case SymbolType_NOT:
		{
			if (p->value == '!') ++p; else p = 0;
			if (p)
			{
				p = Parse(SymbolType_Spacing, p);
			}
		  return p;
		}

		case SymbolType_OPEN:
		{
			if (p->value == '(') ++p; else p = 0;
			if (p)
			{
				p = Parse(SymbolType_Spacing, p);
			}
		  return p;
		}

		case SymbolType_PLUS:
		{
			if (p->value == '+') ++p; else p = 0;
			if (p)
			{
				p = Parse(SymbolType_Spacing, p);
			}
		  return p;
		}

		case SymbolType_Prefix:
		{
			MemoInsertResult r = p->end.insert(Memo(SymbolType_Prefix, 0));
			if (!r.second) return r.first->second;
			Node* b = p;
			p = Parse(SymbolType_AND, p);
			if (!p)
			{
				p = b;
				p = Parse(SymbolType_NOT, p);
				if (!p)
				{
					p = b;
				}
			}
			if (p)
			{
				p = Parse(SymbolType_Suffix, p);
			}
			r.first->second = p;
		  return p;
		}

		case SymbolType_Primary:
		{
			MemoInsertResult r = p->end.insert(Memo(SymbolType_Primary, 0));
			if (!r.second) return r.first->second;
			Node* b = p;
			p = Parse(SymbolType_Identifier, p);
			if (p)
			{
				p = Parse(SymbolType_Spacing, p);
				if (p)
				{
					Node* b2 = p;
					p = Parse(SymbolType_LEFTARROW, p);
					if (p) p = 0; else p = b2;
				}
			}
			if (!p)
			{
				p = b;
				p = Parse(SymbolType_OPEN, p);
				if (p)
				{
					p = Parse(SymbolType_Expression, p);
					if (p)
					{
						p = Parse(SymbolType_CLOSE, p);
					}
				}
				if (!p)
				{
					p = b;
					p = Parse(SymbolType_Literal, p);
					if (!p)
					{
						p = b;
						p = Parse(SymbolType_Class, p);
						if (!p)
						{
							p = b;
							p = Parse(SymbolType_DOT, p);
						}
					}
				}
			}
			r.first->second = p;
		  return p;
		}

		case SymbolType_QUESTION:
		{
			if (p->value == '?') ++p; else p = 0;
			if (p)
			{
				p = Parse(SymbolType_Spacing, p);
			}
		  return p;
		}

		case SymbolType_Range:
		{
			MemoInsertResult r = p->end.insert(Memo(SymbolType_Range, 0));
			if (!r.second) return r.first->second;
			p = Parse(SymbolType_Char, p);
			if (p)
			{
				Node* b = p;
				if (p->value == '-') ++p; else p = 0;
				if (p)
				{
					p = Parse(SymbolType_Char, p);
				}
				if (!p)
				{
					p = b;
				}
			}
			r.first->second = p;
		  return p;
		}

		case SymbolType_SLASH:
		{
			if (p->value == '/') ++p; else p = 0;
			if (p)
			{
				p = Parse(SymbolType_Spacing, p);
			}
		  return p;
		}

		case SymbolType_STAR:
		{
			if (p->value == '*') ++p; else p = 0;
			if (p)
			{
				p = Parse(SymbolType_Spacing, p);
			}
		  return p;
		}

		case SymbolType_Sequence:
		{
			MemoInsertResult r = p->end.insert(Memo(SymbolType_Sequence, 0));
			if (!r.second) return r.first->second;
			for (;;)
			{
				Node* b = p;
				p = Parse(SymbolType_Prefix, p);
				if (!p)
				{
					p = b;
					break;
				}
			}
			r.first->second = p;
		  return p;
		}

		case SymbolType_Space:
		{
			Node* b = p;
			if (p->value == ' ') ++p; else p = 0;
			if (!p)
			{
				p = b;
				if (p->value == '\t') ++p; else p = 0;
				if (!p)
				{
					p = b;
					p = Parse(SymbolType_EndOfLine, p);
				}
			}
		  return p;
		}

		case SymbolType_Spacing:
		{
			MemoInsertResult r = p->end.insert(Memo(SymbolType_Spacing, 0));
			if (!r.second) return r.first->second;
			for (;;)
			{
				Node* b = p;
				p = Parse(SymbolType_Space, p);
				if (!p)
				{
					p = b;
					p = Parse(SymbolType_Comment, p);
				}
				if (!p)
				{
					p = b;
					break;
				}
			}
			r.first->second = p;
		  return p;
		}

		case SymbolType_Suffix:
		{
			MemoInsertResult r = p->end.insert(Memo(SymbolType_Suffix, 0));
			if (!r.second) return r.first->second;
			p = Parse(SymbolType_Primary, p);
			if (p)
			{
				Node* b = p;
				p = Parse(SymbolType_QUESTION, p);
				if (!p)
				{
					p = b;
					p = Parse(SymbolType_STAR, p);
					if (!p)
					{
						p = b;
						p = Parse(SymbolType_PLUS, p);
						if (!p)
						{
							p = b;
						}
					}
				}
			}
			r.first->second = p;
		  return p;
		}

		default:
			assert(false);
			return 0;
	}
}

PEGParser::Node* PEGParser::Parser::Traverse(PEGParser::SymbolType _type, PEGParser::Node* p, PEGParser::PTNodeChildren& v)
{
	switch (_type)
	{
		case SymbolType_Class:
		{
			MemoInsertResult r = p->end.insert(Memo(SymbolType_Class, 0));
			if (!r.second && !r.first->second) return 0;
			if (p->value == '[') ++p; else p = 0;
			if (p)
			{
				for (;;)
				{
					Node* b = p;
					size_t s = v.size();
					if (p->value == ']') ++p; else p = 0;
					if (p) p = 0; else p = b;
					if (p)
					{
						p = Visit(SymbolType_Range, p, v);
					}
					if (!p)
					{
						p = b;
						v.erase(v.begin() + s, v.end());
						break;
					}
				}
				if (p)
				{
					if (p->value == ']') ++p; else p = 0;
					if (p)
					{
						p = Parse(SymbolType_Spacing, p);
					}
				}
			}
			r.first->second = p;
			return p;
		}

		case SymbolType_Definition:
		{
			MemoInsertResult r = p->end.insert(Memo(SymbolType_Definition, 0));
			if (!r.second && !r.first->second) return 0;
			p = Visit(SymbolType_Identifier, p, v);
			if (p)
			{
				p = Parse(SymbolType_Spacing, p);
				if (p)
				{
					p = Visit(SymbolType_LEFTARROW, p, v);
					if (p)
					{
						p = Visit(SymbolType_Expression, p, v);
					}
				}
			}
			r.first->second = p;
			return p;
		}

		case SymbolType_Expression:
		{
			MemoInsertResult r = p->end.insert(Memo(SymbolType_Expression, 0));
			if (!r.second && !r.first->second) return 0;
			p = Visit(SymbolType_Sequence, p, v);
			if (p)
			{
				for (;;)
				{
					Node* b = p;
					size_t s = v.size();
					p = Parse(SymbolType_SLASH, p);
					if (p)
					{
						p = Visit(SymbolType_Sequence, p, v);
					}
					if (!p)
					{
						p = b;
						v.erase(v.begin() + s, v.end());
						break;
					}
				}
			}
			r.first->second = p;
			return p;
		}

		case SymbolType_Grammar:
		{
			MemoInsertResult r = p->end.insert(Memo(SymbolType_Grammar, 0));
			if (!r.second && !r.first->second) return 0;
			p = Parse(SymbolType_Spacing, p);
			if (p)
			{
				p = Visit(SymbolType_Definition, p, v);
				if (p)
				{
					for (;;)
					{
						Node* b = p;
						size_t s = v.size();
						p = Visit(SymbolType_Definition, p, v);
						if (!p)
						{
							p = b;
							v.erase(v.begin() + s, v.end());
							break;
						}
					}
					if (p)
					{
						p = Parse(SymbolType_EndOfFile, p);
					}
				}
			}
			r.first->second = p;
			return p;
		}

		case SymbolType_Literal:
		{
			MemoInsertResult r = p->end.insert(Memo(SymbolType_Literal, 0));
			if (!r.second && !r.first->second) return 0;
			Node* b = p;
			size_t s = v.size();
			if (p->value == '\'') ++p; else p = 0;
			if (p)
			{
				for (;;)
				{
					Node* b2 = p;
					size_t s2 = v.size();
					if (p->value == '\'') ++p; else p = 0;
					if (p) p = 0; else p = b2;
					if (p)
					{
						p = Visit(SymbolType_Char, p, v);
					}
					if (!p)
					{
						p = b2;
						v.erase(v.begin() + s2, v.end());
						break;
					}
				}
				if (p)
				{
					if (p->value == '\'') ++p; else p = 0;
					if (p)
					{
						p = Parse(SymbolType_Spacing, p);
					}
				}
			}
			if (!p)
			{
				p = b;
				v.erase(v.begin() + s, v.end());
				if (p->value == '\"') ++p; else p = 0;
				if (p)
				{
					for (;;)
					{
						Node* b3 = p;
						size_t s3 = v.size();
						if (p->value == '\"') ++p; else p = 0;
						if (p) p = 0; else p = b3;
						if (p)
						{
							p = Visit(SymbolType_Char, p, v);
						}
						if (!p)
						{
							p = b3;
							v.erase(v.begin() + s3, v.end());
							break;
						}
					}
					if (p)
					{
						if (p->value == '\"') ++p; else p = 0;
						if (p)
						{
							p = Parse(SymbolType_Spacing, p);
						}
					}
				}
			}
			r.first->second = p;
			return p;
		}

		case SymbolType_Prefix:
		{
			MemoInsertResult r = p->end.insert(Memo(SymbolType_Prefix, 0));
			if (!r.second && !r.first->second) return 0;
			Node* b = p;
			p = Parse(SymbolType_AND, p);
			if (!p)
			{
				p = b;
				p = Parse(SymbolType_NOT, p);
				if (!p)
				{
					p = b;
				}
			}
			if (p)
			{
				p = Visit(SymbolType_Suffix, p, v);
			}
			r.first->second = p;
			return p;
		}

		case SymbolType_Primary:
		{
			MemoInsertResult r = p->end.insert(Memo(SymbolType_Primary, 0));
			if (!r.second && !r.first->second) return 0;
			Node* b = p;
			size_t s = v.size();
			p = Visit(SymbolType_Identifier, p, v);
			if (p)
			{
				p = Parse(SymbolType_Spacing, p);
				if (p)
				{
					Node* b2 = p;
					p = Parse(SymbolType_LEFTARROW, p);
					if (p) p = 0; else p = b2;
				}
			}
			if (!p)
			{
				p = b;
				v.erase(v.begin() + s, v.end());
				p = Parse(SymbolType_OPEN, p);
				if (p)
				{
					p = Visit(SymbolType_Expression, p, v);
					if (p)
					{
						p = Parse(SymbolType_CLOSE, p);
					}
				}
				if (!p)
				{
					p = b;
					v.erase(v.begin() + s, v.end());
					p = Visit(SymbolType_Literal, p, v);
					if (!p)
					{
						p = b;
						v.erase(v.begin() + s, v.end());
						p = Visit(SymbolType_Class, p, v);
						if (!p)
						{
							p = b;
							v.erase(v.begin() + s, v.end());
							p = Parse(SymbolType_DOT, p);
						}
					}
				}
			}
			r.first->second = p;
			return p;
		}

		case SymbolType_Range:
		{
			MemoInsertResult r = p->end.insert(Memo(SymbolType_Range, 0));
			if (!r.second && !r.first->second) return 0;
			p = Visit(SymbolType_Char, p, v);
			if (p)
			{
				Node* b = p;
				size_t s = v.size();
				if (p->value == '-') ++p; else p = 0;
				if (p)
				{
					p = Visit(SymbolType_Char, p, v);
				}
				if (!p)
				{
					p = b;
					v.erase(v.begin() + s, v.end());
				}
			}
			r.first->second = p;
			return p;
		}

		case SymbolType_Sequence:
		{
			MemoInsertResult r = p->end.insert(Memo(SymbolType_Sequence, 0));
			if (!r.second && !r.first->second) return 0;
			for (;;)
			{
				Node* b = p;
				size_t s = v.size();
				p = Visit(SymbolType_Prefix, p, v);
				if (!p)
				{
					p = b;
					v.erase(v.begin() + s, v.end());
					break;
				}
			}
			r.first->second = p;
			return p;
		}

		case SymbolType_Suffix:
		{
			MemoInsertResult r = p->end.insert(Memo(SymbolType_Suffix, 0));
			if (!r.second && !r.first->second) return 0;
			p = Visit(SymbolType_Primary, p, v);
			if (p)
			{
				Node* b = p;
				p = Parse(SymbolType_QUESTION, p);
				if (!p)
				{
					p = b;
					p = Parse(SymbolType_STAR, p);
					if (!p)
					{
						p = b;
						p = Parse(SymbolType_PLUS, p);
						if (!p)
						{
							p = b;
						}
					}
				}
			}
			r.first->second = p;
			return p;
		}

		case SymbolType_AND:
		case SymbolType_CLOSE:
		case SymbolType_Char:
		case SymbolType_Comment:
		case SymbolType_DOT:
		case SymbolType_EndOfFile:
		case SymbolType_EndOfLine:
		case SymbolType_Identifier:
		case SymbolType_LEFTARROW:
		case SymbolType_NOT:
		case SymbolType_OPEN:
		case SymbolType_PLUS:
		case SymbolType_QUESTION:
		case SymbolType_SLASH:
		case SymbolType_STAR:
		case SymbolType_Space:
		case SymbolType_Spacing:
			return Parse(_type, p);

		default:
			assert(false);
			return 0;
	}
}

void PEGParser::Parser::Print(std::ostream& _os, PEGParser::SymbolType _type, PEGParser::Node* _pNode, int _tabs, int _maxLineSize)
{
	PTNodeChildren children;
	Node* pEnd = Traverse(_type, _pNode, children);
	if (!pEnd)
	{
		std::ostringstream oss;
		oss << "Parsing Failed for \"" << SymbolName(_type) << "\"";
		throw std::runtime_error(oss.str());
	}

	int tabCount = _tabs;
	while (tabCount--)
		_os << "    ";

	_os << SymbolName(_type) << ": \"";

	size_t lineSize = 0;
	for (Node* p = _pNode; p != pEnd; ++p)
	{
		_os << EscapeChar(p->value);
		if (++lineSize >= _maxLineSize)
		{
			_os << "...";
			break;
		}
	}

	_os << "\"\n";

	for (PTNodeChildren::iterator i = children.begin(), iEnd = children.end(); i != iEnd; ++i)
		Print(_os, i->first, i->second, _tabs + 1, _maxLineSize);
}

PEGParser::Node* PEGParser::Parser::Visit(PEGParser::SymbolType _type, PEGParser::Node* _p, PEGParser::PTNodeChildren& _v)
{
	Node* pEnd = Parse(_type, _p);
	if (pEnd)
		_v.push_back(PTNodeChild(_type, _p));
	return pEnd;
}

PEGParser::Iterator::Iterator(PEGParser::SymbolType _type, PEGParser::Node* _pNode)
:	mType(_type)
,	mpNode(_pNode)
, mpSiblings(new PTNodeChildren)
, mpParser(new Parser)
{
	if (mpNode && End())
		mpSiblings->push_back(PTNodeChild(mType, mpNode));

	miCurrent = mpSiblings->begin();
}

PEGParser::Iterator::Iterator(const PEGParser::Iterator& _iOther)
: mType(_iOther.mType)
,	mpNode(_iOther.mpNode)
, mpSiblings(_iOther.mpSiblings)
, miCurrent(_iOther.miCurrent)
,	mpParser(_iOther.mpParser)
{
}

PEGParser::Iterator::operator bool() const
{
	return mpNode != 0;
}

PEGParser::Iterator& PEGParser::Iterator::operator++()
{
	mpChildren.reset();
	GoToNext(mType);
	return *this;
}

PEGParser::SymbolType PEGParser::Iterator::GetType() const
{
	return mType;
}

PEGParser::Node* PEGParser::Iterator::Begin() const
{
	assert(mpNode);
	return mpNode;
}

PEGParser::Node* PEGParser::Iterator::End() const
{
	assert(mpNode);
	if (mType == SymbolType(0))
		return mpNode + 1;
	return mpParser->Parse(mType, mpNode);
}

PEGParser::Iterator PEGParser::Iterator::GetChild(PEGParser::SymbolType _childT)
{
	assert(mpNode != 0);
	if (_childT == SymbolType(0))
		return Iterator(SymbolType(0), mpNode);
	else
		return Iterator(mpParser, GetChildren(), _childT);
}

PEGParser::Iterator PEGParser::Iterator::GetNext(PEGParser::SymbolType _childT)
{
	assert(mpNode != 0);
	if (_childT == SymbolType(0))
		return Iterator(SymbolType(0), mpNode + 1);
	else
		return Iterator(*this, _childT);
}

PEGParser::Iterator::Iterator(boost::shared_ptr<PEGParser::Parser> _pParser, boost::shared_ptr<PEGParser::PTNodeChildren> _pSiblings, PEGParser::SymbolType _childType)
: mType(_childType)
, mpSiblings(_pSiblings)
, miCurrent(_pSiblings->begin())
,	mpParser(_pParser)
{
	SkipSiblingsWithWrongType(_childType);
}

PEGParser::Iterator::Iterator(const PEGParser::Iterator& _iOther, PEGParser::SymbolType _childType)
: mType(_childType)
,	mpSiblings(_iOther.mpSiblings)
,	miCurrent(_iOther.miCurrent)
,	mpParser(_iOther.mpParser)
{
	SkipSiblingsWithWrongType(_childType);
}

void PEGParser::Iterator::GoToNext(PEGParser::SymbolType _childType)
{
	if (mType == SymbolType(0))
	{
		++mpNode;
		if (mpNode->value == 0)
			mpNode = 0;
	}
	else
	{
		++miCurrent;
		SkipSiblingsWithWrongType(_childType);
	}
}

void PEGParser::Iterator::SkipSiblingsWithWrongType(PEGParser::SymbolType _childType)
{
	assert(_childType != SymbolType(0));
	PTNodeChildren::iterator iEnd = mpSiblings->end();
	while (miCurrent != iEnd && miCurrent->first != _childType)
		++miCurrent;
	mpNode = (miCurrent != iEnd) ? miCurrent->second : 0 ;
}

boost::shared_ptr<PEGParser::PTNodeChildren> PEGParser::Iterator::GetChildren()
{
	if (!mpChildren)
	{
		PTNodeChildren children;
		mpParser->Traverse(mType, mpNode, children);
		mpChildren.reset(new PTNodeChildren);
		mpChildren->swap(children);			
	}
	return mpChildren;
}

std::ostream& PEGParser::operator<<(std::ostream& _os, const PEGParser::Iterator& _i)
{
	if (_i)
	{
		for (const PEGParser::Node *p = _i.Begin(), *pEnd = _i.End(); p != pEnd; ++p)
			_os.put(p->value);
	}
	return _os;
}

